const KEY='AIzaSyDpG0QJtE6XfnucaHJPhlJQSgxdLEsbSkg
const API='https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key='+KEY;
const state={left:null,right:null,leftType:null,rightType:null,leftData:null,rightData:null};
const $=id=>document.getElementById(id);
function show(id){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));$(id).classList.add('active');scrollTo({top:0,behavior:'smooth'});}function scrollToForm(){$('form').scrollIntoView({behavior:'smooth'});}function loadImage(side,input){const file=input.files[0];if(!file)return;const r=new FileReader();r.onload=e=>{state[side]=e.target.result;state[side+'Data']=e.target.result.split(',')[1];state[side+'Type']=file.type||'image/jpeg';$(side+'Prev').src=e.target.result;$(side+'Card').classList.add('filled');check();};r.readAsDataURL(file);}function check(){const ok=state.left&&state.right&&$('name').value&&$('age').value&&$('gender').value;$('analyzeBtn').disabled=!ok;}['name','age','gender'].forEach(id=>addEventListener('input',check));
function loadingAnim(){let i=0;const items=[...document.querySelectorAll('.scan-list li')];return setInterval(()=>{items.forEach(x=>x.classList.remove('on'));items[Math.min(i,items.length-1)].classList.add('on');i=(i+1)%items.length;},1300)}
const prompt=(name,age,gender)=>`Чи бол Сара нэртэй алганы хээ шинжээч. Монгол хэлээр дулаан, мэргэжлийн, давтагдалгүй тайлан бич. Зураг дээр харагдахгүй зүйлийг баттай мэт зохиохгүй, "ерөнхий ажиглалтаар" гэж болгоомжтой хэл. Хариултыг зөвхөн JSON хэлбэрээр өг. Нэр: ${name}, Нас: ${age}, Хүйс: ${gender}. JSON бүтэц: {"summary":"ерөнхий 5-7 өгүүлбэр", "lineNotes":{"heart":"зүрхний шугамын 2-3 өгүүлбэр", "head":"толгойн шугамын 2-3 өгүүлбэр", "life":"амьдралын шугамын 2-3 өгүүлбэр", "fate":"хувь заяаны шугамын 2-3 өгүүлбэр", "sun":"нарны шугамын 2-3 өгүүлбэр"}, "scores":{"Хайр дурлал":88,"Санхүү":76,"Карьер":82,"Эрүүл мэнд":79,"Тогтвортой байдал":84}, "timeline":[{"age":"Одоо - ${age} нас","text":"...","advice":"..."},{"age":"${Number(age)+1} - ${Number(age)+2} нас","text":"...","advice":"..."},{"age":"${Number(age)+3} - ${Number(age)+4} нас","text":"...","advice":"..."}], "sections":[{"title":"Ерөнхий дүр зураг","body":"120-180 үг"},{"title":"Зан чанар","body":"120-180 үг"},{"title":"Хайр дурлал","body":"120-180 үг"},{"title":"Ажил мэргэжил","body":"120-180 үг"},{"title":"Мөнгө санхүү","body":"120-180 үг"},{"title":"Эрүүл мэндийн хандлага","body":"Эмнэлгийн онош биш, уламжлалт тайлалын хүрээнд 100-150 үг"},{"title":"Давуу тал","body":"100-150 үг"},{"title":"Анхаарах зүйл","body":"100-150 үг"},{"title":"3 жилийн ерөнхий төлөв","body":"150-220 үг"},{"title":"Сарагийн хувийн зөвлөгөө","body":"120-180 үг"}], "quote":"богино урамтай ишлэл"}`;
async function startAnalysis(){hideError();const name=$('name').value.trim(),age=$('age').value,gender=$('gender').value;show('loading');const timer=loadingAnim();try{const res=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt(name,age,gender)},{inline_data:{mime_type:state.leftType,data:state.leftData}},{inline_data:{mime_type:state.rightType,data:state.rightData}}]}],generationConfig:{temperature:.65,maxOutputTokens:8192,response_mime_type:'application/json'}})});const data=await res.json();if(!res.ok)throw new Error(data.error?.message||'AI холболтын алдаа');let txt=data.candidates?.[0]?.content?.parts?.[0]?.text||'';txt=txt.replace(/```json|```/g,'').trim();let report;try{report=JSON.parse(txt)}catch(e){report=fallbackReport(name,age,gender,txt)}clearInterval(timer);renderReport(report,name,age,gender);show('result');}catch(e){clearInterval(timer);show('start');showError('Алдаа: '+e.message);}}
function fallbackReport(name,age,gender,txt){return{summary:txt||`${name} таны алганы ерөнхий хэлбэрээс тогтвортой, бодитой, мэдрэмжтэй зан төлөв ажиглагдаж байна.`,lineNotes:{heart:'Сэтгэлийн илэрхийлэл тогтуун, харилцаанд үнэнч байдлыг эрхэмлэх хандлагатай.',head:'Бодол санаа практик, шийдвэр гаргахдаа ажиглаж тунгаах тал давамгай.',life:'Амьдралын хэмнэл тогтвортой, хүчээ зөв хуваарилах хэрэгтэй.',fate:'Зорилгоо тодруулбал ажил, санхүүгийн зам илүү цэгцтэй болно.',sun:'Авьяас чадвар аажмаар тодрох шинжтэй.'},scores:{'Хайр дурлал':88,'Санхүү':78,'Карьер':84,'Эрүүл мэнд':76,'Тогтвортой байдал':82},timeline:[{age:`Одоо - ${age} нас`,text:'Одоо байгаа сонголтоо цэгцлэх үе.',advice:'Дотоод хүчээ зөв зүйлд чиглүүл.'},{age:`${+age+1} - ${+age+2} нас`,text:'Ажил, санхүү, харилцаанд шинэ боломж нэмэгдэнэ.',advice:'Шинэ төлөвлөгөөнд зоригтой ор.'},{age:`${+age+3} - ${+age+4} нас`,text:'Өмнөх хөдөлмөрийн үр дүн тогтох үе.',advice:'Тогтвортой систем бүтээ.'}],sections:[{title:'Ерөнхий дүр зураг',body:txt||'Таны хоёр гарын ерөнхий хэлбэр, үндсэн шугамуудын байрлал нь бодитой, мэдрэмжтэй, хариуцлагатай хандлагыг илтгэнэ.'},{title:'Сарагийн хувийн зөвлөгөө',body:'Өөрийн замаа яаралгүй, гэхдээ итгэлтэйгээр бүтээ. Төлөвлөгөө, сахилга бат, харилцааны үнэнч байдал таны гол түлхүүр байна.'}],quote:'Алга тань таны замын газрын зураг юм.'}}
function renderReport(r,name,age,gender){$('meta').textContent=`${name} / ${gender} / ${age} нас`;drawPalm();$('l1').textContent=r.lineNotes?.heart||'';$('l2').textContent=r.lineNotes?.head||'';$('l3').textContent=r.lineNotes?.life||'';$('l4').textContent=r.lineNotes?.fate||'';$('l5').textContent=r.lineNotes?.sun||'';renderScores(r.scores);renderTimeline(r.timeline);renderSections(r.sections,r.summary);$('quote').textContent='“'+(r.quote||'Алганы хээ бол таны амьдралын газрын зураг юм.')+'”';}
function drawPalm(){const canvas=$('palmCanvas'),ctx=canvas.getContext('2d'),img=new Image();img.onload=()=>{const maxW=900;const scale=Math.min(1,maxW/img.width);canvas.width=img.width*scale;canvas.height=img.height*scale;ctx.drawImage(img,0,0,canvas.width,canvas.height);const w=canvas.width,h=canvas.height;ctx.lineWidth=Math.max(4,w*.009);ctx.lineCap='round';function curve(color,pts){ctx.strokeStyle=color;ctx.beginPath();ctx.moveTo(pts[0][0]*w,pts[0][1]*h);for(let i=1;i<pts.length-1;i++){ctx.quadraticCurveTo(pts[i][0]*w,pts[i][1]*h,pts[i+1][0]*w,pts[i+1][1]*h)}ctx.stroke()}curve('#ef5b5b',[[.24,.47],[.44,.44],[.78,.49]]);curve('#2f8ccf',[[.20,.55],[.43,.52],[.70,.62]]);curve('#2aa66a',[[.30,.62],[.25,.75],[.38,.91]]);curve('#f2a71b',[[.55,.42],[.56,.58],[.56,.82]]);curve('#8b4bd6',[[.61,.55],[.60,.68],[.60,.86]]);[[1,.47,.49,'#ef5b5b'],[2,.22,.56,'#2f8ccf'],[3,.34,.73,'#2aa66a'],[4,.78,.49,'#f2a71b'],[5,.60,.69,'#8b4bd6']].forEach(([n,x,y,c])=>{ctx.fillStyle=c;ctx.beginPath();ctx.arc(x*w,y*h,Math.max(14,w*.032),0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font=`bold ${Math.max(16,w*.035)}px Inter`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(n,x*w,y*h)});};img.src=state.right||state.left;}
function renderScores(scores={}){const colors=['#ef5b5b','#2aa66a','#2f8ccf','#86c8b0','#f2a71b'];$('scores').innerHTML=Object.entries(scores).slice(0,5).map(([k,v],i)=>`<div class="score"><b>${k}</b><div class="ring" style="--p:${Number(v)||80};--c:${colors[i]}" data-val="${Number(v)||80}"></div><small>${v>=88?'Маш сайн':v>=75?'Сайн':'Анхаарах'}</small></div>`).join('')}
function renderTimeline(arr=[]){$('timeline').innerHTML=arr.slice(0,3).map(t=>`<div class="timebox"><h3>${t.age||''}</h3><p>${t.text||''}</p><small><b>Зөвлөмж</b><br>${t.advice||''}</small></div>`).join('')}
function renderSections(arr=[],summary=''){let html=summary?`<article class="section"><h2>Ерөнхий дүгнэлт</h2><p>${summary}</p></article>`:'';html+=arr.map(s=>`<article class="section"><h2>${s.title}</h2><p>${s.body}</p></article>`).join('');$('sections').innerHTML=html;}
function showError(msg){$('error').style.display='block';$('error').textContent=msg}function hideError(){$('error').style.display='none'}function resetApp(){location.reload()}
async function downloadPDF(){const report=$('report');const canvas=await html2canvas(report,{scale:1.5,useCORS:true,backgroundColor:'#faf8f4'});const img=canvas.toDataURL('image/jpeg',.92);const {jsPDF}=window.jspdf;const pdf=new jsPDF('p','mm','a4');const pageW=210,pageH=297;const imgW=pageW;const imgH=canvas.height*imgW/canvas.width;let y=0;pdf.addImage(img,'JPEG',0,y,imgW,imgH);let left=imgH-pageH;while(left>0){y-=pageH;pdf.addPage();pdf.addImage(img,'JPEG',0,y,imgW,imgH);left-=pageH}pdf.save('sara-palm-report.pdf')}
if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{})}
