const $=id=>document.getElementById(id);
const state={left:null,right:null,leftType:null,rightType:null,report:null};
const steps=['Амьдралын шугам илрүүлж байна','Толгойн шугам шинжилж байна','Зүрхний шугам уншиж байна','Ховор тэмдэг хайж байна','PDF тайлангийн бүтэц үүсгэж байна'];
const legends={life:'Амьдралын шугам нь эрч хүч, тэсвэр, амьдралын хэмнэлийн чиглэлийг бэлгэддэг. Энэ зураглал нь таны гар дээр тайлбарлахад зориулсан визуал тэмдэглэгээ юм.',head:'Толгойн шугам нь бодол, шийдвэр гаргалт, суралцах арга барилтай холбогдон тайлбарлагддаг.',heart:'Зүрхний шугам нь хайр, мэдрэмж, дотоод уян чанар, харилцааны хэв маягтай холбоотой.',fate:'Хувь тавилангийн шугам нь ажил, зорилго, зам мөрийн тогтвортой байдлын бэлгэдэл гэж үздэг.',sun:'Нарны шугам нь авьяас, нэр хүнд, бүтээлч илэрхийлэл, бусдад харагдах чадварыг илтгэнэ.'};
function fileToData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
async function handle(file,side){if(!file)return;const data=await fileToData(file);state[side]=data;state[side+'Type']=file.type||'image/jpeg';const img=$(side+'Preview');img.src=data;img.parentElement.classList.add('has');}
['leftFile','leftCam'].forEach(id=>$(id).addEventListener('change',e=>handle(e.target.files[0],'left')));
['rightFile','rightCam'].forEach(id=>$(id).addEventListener('change',e=>handle(e.target.files[0],'right')));
$('apiKey').value=localStorage.getItem('sara_gemini_key')||'';
$('saveKey').onclick=()=>{localStorage.setItem('sara_gemini_key',$('apiKey').value.trim());alert('API key хадгалагдлаа')};
document.querySelectorAll('.legend button').forEach(b=>b.onclick=()=>{$('legendText').textContent=legends[b.dataset.key]});
$('analyzeBtn').onclick=async()=>{const name=$('clientName').value.trim(),age=$('age').value.trim(),gender=$('gender').value;if(!name||!age||!gender||!state.left||!state.right){alert('Нэр, нас, хүйс болон хоёр гарын зургаа оруулна уу.');return}showScan();try{const data=await callGemini(name,age,gender);render(data,name,age,gender)}catch(e){console.warn(e);render(demoReport(name,age,gender),name,age,gender)}};
function showScan(){$('scan').hidden=false;$('report').hidden=true;$('scan').scrollIntoView({behavior:'smooth'});let i=0;const t=setInterval(()=>{i++;$('scanText').textContent=steps[Math.min(i,steps.length-1)];$('barFill').style.width=Math.min(100,(i+1)*22)+'%';if(i>=steps.length)clearInterval(t)},650)}
async function callGemini(name,age,gender){const key=(localStorage.getItem('sara_gemini_key')||$('apiKey').value||'').trim();if(!key)throw new Error('No key');const prompt=`Та мэргэжлийн алганы хээ шинжээч Сара. Монгол хэлээр цэвэр, давтагдалгүй, дулаан боловч мэргэжлийн тайлан бич. Хэрэглэгч: ${name}, нас ${age}, хүйс ${gender}. Зүүн ба баруун гарын зураг хавсаргасан. Харагдахгүй зүйлийг зохиохгүй. JSON хэлбэрээр яг дараах бүтэцтэй буцаа: {"scores":{"Хайр":82,"Санхүү":76,"Карьер":84,"Эрүүл мэнд":73,"Аз хийморь":88},"timeline":[{"period":"Одоо","text":"..."},{"period":"1 жил","text":"..."},{"period":"2-3 жил","text":"..."}],"sections":[{"title":"Ерөнхий дүр зураг","text":"..."}]} sections-д дор хаяж 18 хэсэг оруул: Ерөнхий дүр зураг, Зүүн гар, Баруун гар, Хоёр гарын ялгаа, Амьдралын шугам, Толгойн шугам, Зүрхний шугам, Хувь тавилангийн шугам, Нарны шугам, Мөнгөний шугам, Алганы уулсууд, Хурууны хэлбэр, Ховор тэмдэг, Давуу тал, Анхаарах тал, Хайр дурлал, Санхүү, Ажил мэргэжил, Амьдралын үе шат, Сарагийн зөвлөгөө.`;
 const body={contents:[{parts:[{text:prompt},{inline_data:{mime_type:state.leftType,data:state.left.split(',')[1]}},{inline_data:{mime_type:state.rightType,data:state.right.split(',')[1]}}]}],generationConfig:{temperature:.75,maxOutputTokens:8192,responseMimeType:'application/json'}};
 const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
 if(!res.ok)throw new Error(await res.text());const j=await res.json();return JSON.parse(j.candidates?.[0]?.content?.parts?.[0]?.text||'{}')}
function demoReport(name,age,gender){return {scores:{'Хайр':82,'Санхүү':76,'Карьер':84,'Эрүүл мэнд':73,'Аз хийморь':88},timeline:[{period:'Одоо',text:'Өөрийн чиглэлээ илүү тодорхой болгох, эхлүүлсэн зүйлээ дуусгах үе.'},{period:'1 жил',text:'Ажил, харилцаа, санхүүгийн хувьд тогтвортой алхам хийх боломж нэмэгдэнэ.'},{period:'2–3 жил',text:'Өмнөх хөдөлмөрийн үр дүн илүү тодорч, нэр хүнд ба итгэл нэмэгдэх хандлагатай.'}],sections:['Ерөнхий дүр зураг','Зүүн гар','Баруун гар','Хоёр гарын ялгаа','Амьдралын шугам','Толгойн шугам','Зүрхний шугам','Хувь тавилангийн шугам','Нарны шугам','Мөнгөний шугам','Алганы уулсууд','Хурууны хэлбэр','Ховор тэмдэг','Давуу тал','Анхаарах тал','Хайр дурлал','Санхүү','Ажил мэргэжил','Амьдралын үе шат','Сарагийн зөвлөгөө'].map(t=>({title:t,text:`${name}-ийн илгээсэн алганы зураг дээр үндэслэсэн энэхүү хэсэг нь ${t.toLowerCase()}-ийн талаарх ерөнхий чиг хандлагыг тайлбарлана. Зураг тод байх тусам тайлбар илүү нарийвчлалтай гарна. Энэ хэсгийг Gemini API key оруулсны дараа AI таны бодит зураг дээр тулгуурлан илүү дэлгэрэнгүй бичнэ.`}))}}
function render(data,name,age,gender){$('scan').hidden=true;$('report').hidden=false;$('metaText').textContent=`${name} · ${age} нас · ${gender} · ${new Date().toLocaleDateString('mn-MN')}`;$('mainPalm').src=state.right||state.left;renderScores(data.scores||{});renderTimeline(data.timeline||[]);renderSections(data.sections||[]);$('report').scrollIntoView({behavior:'smooth'})}
function renderScores(scores){$('scores').innerHTML=Object.entries(scores).map(([k,v])=>`<div class="score"><span>${k}</span><b>${v}%</b><div class="meter"><i style="width:${Math.max(5,Math.min(100,Number(v)||0))}%"></i></div></div>`).join('')}
function renderTimeline(items){$('timeline').innerHTML='<div class="section-title"><p>Амьдралын үе шат</p><h2>Ойрын чиг хандлага</h2></div>'+items.map(x=>`<div class="time-item"><b>${x.period}</b><span>${x.text}</span></div>`).join('')}
function renderSections(items){$('sections').innerHTML=items.map(x=>`<article class="card"><h3>${x.title}</h3><p>${x.text}</p></article>`).join('')}
if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{})}
