const DEFAULT_KEY='';
function getApiUrl(){
  let key=localStorage.getItem('GEMINI_API_KEY') || DEFAULT_KEY;
  if(!key){
    key=window.prompt('Gemini API key-гээ оруулна уу');
    if(!key) throw new Error('API key оруулаагүй байна');
    localStorage.setItem('GEMINI_API_KEY', key.trim());
  }
  return 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key='+encodeURIComponent(key.trim());
}

const state={left:null,right:null,leftType:null,rightType:null,leftData:null,rightData:null};
let currentReport=null;
let currentMeta={name:'',age:'',gender:'',date:''};
const $=id=>document.getElementById(id);

function show(id){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));$(id).classList.add('active');scrollTo({top:0,behavior:'smooth'});}
function scrollToForm(){$('form').scrollIntoView({behavior:'smooth'});}
function loadImage(side,input){const file=input.files[0];if(!file)return;const r=new FileReader();r.onload=e=>{state[side]=e.target.result;state[side+'Data']=e.target.result.split(',')[1];state[side+'Type']=file.type||'image/jpeg';$(side+'Prev').src=e.target.result;$(side+'Card').classList.add('filled');check();};r.readAsDataURL(file);}
function check(){const ok=state.left&&state.right&&$('name').value&&$('age').value&&$('gender').value;$('analyzeBtn').disabled=!ok;}
['name','age','gender'].forEach(id=>$(id).addEventListener('input',check));
function loadingAnim(){let i=0;const items=[...document.querySelectorAll('.scan-list li')];return setInterval(()=>{items.forEach(x=>x.classList.remove('on'));items[Math.min(i,items.length-1)].classList.add('on');i=(i+1)%items.length;},1300)}
function formatMongolianDate(d=new Date()){return `${d.getFullYear()} оны ${d.getMonth()+1} сарын ${d.getDate()} өдөр`;}
function buildMeta(name,age,gender){return `${name} / ${gender} / ${age} нас / Тайлан авсан огноо: ${formatMongolianDate()}`;}
function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[m]));}

const prompt=(name,age,gender)=>`Чи бол Сара нэртэй алганы хээ шинжээч. Монгол хэлээр дулаан, мэргэжлийн, давтагдалгүй тайлан бич. Зураг дээр харагдахгүй зүйлийг баттай мэт зохиохгүй, "ерөнхий ажиглалтаар" гэж болгоомжтой хэл. Хариултыг зөвхөн JSON хэлбэрээр өг. Нэр: ${name}, Нас: ${age}, Хүйс: ${gender}. JSON бүтэц: {"summary":"ерөнхий 5-7 өгүүлбэр", "lineNotes":{"heart":"зүрхний шугамын 2-3 өгүүлбэр", "head":"толгойн шугамын 2-3 өгүүлбэр", "life":"амьдралын шугамын 2-3 өгүүлбэр", "fate":"хувь заяаны шугамын 2-3 өгүүлбэр", "sun":"нарны шугамын 2-3 өгүүлбэр"}, "scores":{"Хайр дурлал":88,"Санхүү":76,"Карьер":82,"Эрүүл мэнд":79,"Тогтвортой байдал":84}, "timeline":[{"age":"Одоо - ${age} нас","text":"...","advice":"..."},{"age":"${Number(age)+1} - ${Number(age)+2} нас","text":"...","advice":"..."},{"age":"${Number(age)+3} - ${Number(age)+4} нас","text":"...","advice":"..."}], "sections":[{"title":"Ерөнхий дүр зураг","body":"180-250 үг"},{"title":"Зан чанар","body":"160-220 үг"},{"title":"Дотоод хүч ба төвлөрөл","body":"140-200 үг"},{"title":"Хайр дурлал","body":"160-220 үг"},{"title":"Ханийн заяа","body":"140-200 үг"},{"title":"Гэр бүл, харилцаа","body":"140-200 үг"},{"title":"Ажил мэргэжил","body":"160-230 үг"},{"title":"Бизнесийн боломж","body":"140-200 үг"},{"title":"Мөнгө санхүү","body":"160-230 үг"},{"title":"Мөнгө тогтоох хандлага","body":"140-200 үг"},{"title":"Эрүүл мэндийн хандлага","body":"Эмнэлгийн онош биш, уламжлалт тайлалын хүрээнд 130-190 үг"},{"title":"Давуу тал","body":"130-190 үг"},{"title":"Сул тал ба анхаарах зүйл","body":"130-190 үг"},{"title":"Аз хийморийн ерөнхий өнгө","body":"130-190 үг"},{"title":"Амьдралын 3 жилийн төлөв","body":"180-260 үг"},{"title":"2026 оны чиглэл","body":"130-190 үг"},{"title":"2027 оны чиглэл","body":"130-190 үг"},{"title":"2028 оны чиглэл","body":"130-190 үг"},{"title":"Сарагийн хувийн зөвлөгөө","body":"160-230 үг"},{"title":"Эцсийн дүгнэлт","body":"160-230 үг"}], "quote":"богино урамтай ишлэл"}`;

function parseAiReport(txt,name,age,gender){txt=(txt||'').replace(/```json|```/g,'').trim();try{return JSON.parse(txt)}catch(e){}const first=txt.indexOf('{'), last=txt.lastIndexOf('}');if(first>=0&&last>first){try{return JSON.parse(txt.slice(first,last+1))}catch(e){}}return fallbackReport(name,age,gender,txt);}

async function startAnalysis(){hideError();const name=$('name').value.trim(),age=$('age').value,gender=$('gender').value;show('loading');const timer=loadingAnim();try{const res=await fetch(getApiUrl(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt(name,age,gender)},{inline_data:{mime_type:state.leftType,data:state.leftData}},{inline_data:{mime_type:state.rightType,data:state.rightData}}]}],generationConfig:{temperature:.65,maxOutputTokens:8192,response_mime_type:'application/json'}})});const data=await res.json();if(!res.ok){const msg=data.error?.message||'AI холболтын алдаа';if(msg.toLowerCase().includes('leak')||msg.toLowerCase().includes('api key'))localStorage.removeItem('GEMINI_API_KEY');throw new Error(msg);}let txt=data.candidates?.[0]?.content?.parts?.[0]?.text||'';let report=parseAiReport(txt,name,age,gender);clearInterval(timer);renderReport(report,name,age,gender);show('result');}catch(e){clearInterval(timer);show('start');showError('Алдаа: '+e.message);}}

function fallbackReport(name,age,gender,txt){return{summary:txt||`${name} таны алганы ерөнхий хэлбэрээс тогтвортой, бодитой, мэдрэмжтэй зан төлөв ажиглагдаж байна.`,lineNotes:{heart:'Сэтгэлийн илэрхийлэл тогтуун, харилцаанд үнэнч байдлыг эрхэмлэх хандлагатай.',head:'Бодол санаа практик, шийдвэр гаргахдаа ажиглаж тунгаах тал давамгай.',life:'Амьдралын хэмнэл тогтвортой, хүчээ зөв хуваарилах хэрэгтэй.',fate:'Зорилгоо тодруулбал ажил, санхүүгийн зам илүү цэгцтэй болно.',sun:'Авьяас чадвар аажмаар тодрох шинжтэй.'},scores:{'Хайр дурлал':88,'Санхүү':78,'Карьер':84,'Эрүүл мэнд':76,'Тогтвортой байдал':82},timeline:[{age:`Одоо - ${age} нас`,text:'Одоо байгаа сонголтоо цэгцлэх үе.',advice:'Дотоод хүчээ зөв зүйлд чиглүүл.'},{age:`${+age+1} - ${+age+2} нас`,text:'Ажил, санхүү, харилцаанд шинэ боломж нэмэгдэнэ.',advice:'Шинэ төлөвлөгөөнд зоригтой ор.'},{age:`${+age+3} - ${+age+4} нас`,text:'Өмнөх хөдөлмөрийн үр дүн тогтох үе.',advice:'Тогтвортой систем бүтээ.'}],sections:[{title:'Ерөнхий дүр зураг',body:txt||'Таны хоёр гарын ерөнхий хэлбэр, үндсэн шугамуудын байрлал нь бодитой, мэдрэмжтэй, хариуцлагатай хандлагыг илтгэнэ.'},{title:'Сарагийн хувийн зөвлөгөө',body:'Өөрийн замаа яаралгүй, гэхдээ итгэлтэйгээр бүтээ. Төлөвлөгөө, сахилга бат, харилцааны үнэнч байдал таны гол түлхүүр байна.'}],quote:'Алга тань таны замын газрын зураг юм.'}}

function renderReport(r,name,age,gender){currentReport=r;currentMeta={name,age,gender,date:formatMongolianDate()};$('meta').textContent=buildMeta(name,age,gender);drawPalm();$('l1').textContent=r.lineNotes?.heart||'';$('l2').textContent=r.lineNotes?.head||'';$('l3').textContent=r.lineNotes?.life||'';$('l4').textContent=r.lineNotes?.fate||'';$('l5').textContent=r.lineNotes?.sun||'';renderScores(r.scores);renderTimeline(r.timeline);renderSections(r.sections,r.summary);$('quote').textContent='“'+(r.quote||'Алганы хээ бол таны амьдралын газрын зураг юм.')+'”';}

function drawPalm(){const canvas=$('palmCanvas'),ctx=canvas.getContext('2d'),img=new Image();img.onload=()=>{const maxW=900;const scale=Math.min(1,maxW/img.width);canvas.width=img.width*scale;canvas.height=img.height*scale;ctx.drawImage(img,0,0,canvas.width,canvas.height);const w=canvas.width,h=canvas.height;ctx.lineWidth=Math.max(4,w*.009);ctx.lineCap='round';function curve(color,pts){ctx.strokeStyle=color;ctx.beginPath();ctx.moveTo(pts[0][0]*w,pts[0][1]*h);for(let i=1;i<pts.length-1;i++){ctx.quadraticCurveTo(pts[i][0]*w,pts[i][1]*h,pts[i+1][0]*w,pts[i+1][1]*h)}ctx.stroke()}curve('#ef5b5b',[[.24,.47],[.44,.44],[.78,.49]]);curve('#2f8ccf',[[.20,.55],[.43,.52],[.70,.62]]);curve('#2aa66a',[[.30,.62],[.25,.75],[.38,.91]]);curve('#f2a71b',[[.55,.42],[.56,.58],[.56,.82]]);curve('#8b4bd6',[[.61,.55],[.60,.68],[.60,.86]]);[[1,.47,.49,'#ef5b5b'],[2,.22,.56,'#2f8ccf'],[3,.34,.73,'#2aa66a'],[4,.78,.49,'#f2a71b'],[5,.60,.69,'#8b4bd6']].forEach(([n,x,y,c])=>{ctx.fillStyle=c;ctx.beginPath();ctx.arc(x*w,y*h,Math.max(14,w*.032),0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font=`bold ${Math.max(16,w*.035)}px Inter`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(n,x*w,y*h)});};img.src=state.right||state.left;}
function renderScores(scores={}){const colors=['#ef5b5b','#2aa66a','#2f8ccf','#86c8b0','#f2a71b'];$('scores').innerHTML=Object.entries(scores).slice(0,5).map(([k,v],i)=>`<div class="score"><b>${esc(k)}</b><div class="ring" style="--p:${Number(v)||80};--c:${colors[i]}" data-val="${Number(v)||80}"></div><small>${v>=88?'Маш сайн':v>=75?'Сайн':'Анхаарах'}</small></div>`).join('')}
function renderTimeline(arr=[]){$('timeline').innerHTML=arr.slice(0,3).map(t=>`<div class="timebox"><h3>${esc(t.age||'')}</h3><p>${esc(t.text||'')}</p><small><b>Зөвлөмж</b><br>${esc(t.advice||'')}</small></div>`).join('')}
function renderSections(arr=[],summary=''){let html=summary?`<article class="section"><h2>Ерөнхий дүгнэлт</h2><p>${esc(summary)}</p></article>`:'';html+=arr.map(s=>`<article class="section"><h2>${esc(s.title)}</h2><p>${esc(s.body)}</p></article>`).join('');$('sections').innerHTML=html;}
function showError(msg){$('error').style.display='block';$('error').textContent=msg}function hideError(){$('error').style.display='none'}function resetApp(){location.reload()}

function lineNotesHtml(r){const n=r.lineNotes||{};const items=[['1','Зүрхний шугам',n.heart],['2','Толгойн шугам',n.head],['3','Амьдралын шугам',n.life],['4','Хувь заяаны шугам',n.fate],['5','Нарны шугам',n.sun]];return `<div class="line-notes">${items.map(x=>`<div><b>${x[0]}</b><strong>${esc(x[1])}</strong><p>${esc(x[2]||'')}</p></div>`).join('')}</div>`;}
function scoresHtml(scores={}){return `<div class="pdf-grid">${Object.entries(scores).slice(0,5).map(([k,v])=>`<div class="mini"><b>${esc(k)}</b><p>${Number(v)||80}%</p><small>${v>=88?'Маш сайн':v>=75?'Сайн':'Анхаарах'}</small></div>`).join('')}</div>`;}
function timelineHtml(arr=[]){return `<div>${arr.slice(0,3).map(t=>`<div class="box"><h3>${esc(t.age||'')}</h3><p>${esc(t.text||'')}</p><small><b>Зөвлөмж:</b> ${esc(t.advice||'')}</small></div>`).join('')}</div>`;}
function getPalmImage(){const c=$('palmCanvas');try{return c&&c.width?c.toDataURL('image/jpeg',0.92):(state.right||state.left||'');}catch(e){return state.right||state.left||'';}}
function buildPrintDocument(){const r=currentReport||fallbackReport(currentMeta.name||'',currentMeta.age||'',currentMeta.gender||'','');const m=currentMeta;const palmImg=getPalmImage();const pages=[];function page(title,body,cls=''){pages.push(`<section class="page ${cls}">${title?`<h2>${esc(title)}</h2>`:''}<div class="page-body">${body}</div><footer><span>Системийн зохиогч: Л.Батцог</span><span></span></footer></section>`)}
  pages.push(`<section class="page cover"><div class="brand">Сара</div><h1>Хувь Тавилангийн Хээ</h1><p>Алганы хээний дэлгэрэнгүй тайлан</p><div class="client"><h2>Үйлчлүүлэгчийн мэдээлэл</h2><p><b>Нэр:</b> ${esc(m.name)}</p><p><b>Нас:</b> ${esc(m.age)}</p><p><b>Хүйс:</b> ${esc(m.gender)}</p><p><b>Тайлан авсан огноо:</b> ${esc(m.date)}</p></div><footer><span>Сара</span><span>Системийн зохиогч: Л.Батцог</span></footer></section>`);
  page('Алганы хээний зураглал',`<img class="palm-img" src="${palmImg}"><p class="hint">Нэг гарын зураг дээр үндсэн шугамуудыг өнгөөр тэмдэглэн тайлбарлав.</p>${lineNotesHtml(r)}`,'palm-page');
  page('Ерөнхий төлөвийн оноо',scoresHtml(r.scores));
  page('Амьдралын үе шат',timelineHtml(r.timeline));
  if(r.summary) page('Ерөнхий дүгнэлт',`<p>${esc(r.summary)}</p>`);
  (r.sections||[]).forEach(s=>page(s.title||'Дэд хэсэг',`<p>${esc(s.body||'')}</p>`));
  page('Сарагийн үг',`<blockquote>“${esc(r.quote||'Алганы хээ бол таны амьдралын газрын зураг юм.')}”</blockquote>`);
  const css=`@page{size:A4;margin:14mm}*{box-sizing:border-box}body{margin:0;background:#fffdf9;color:#1f3f3a;font-family:Inter,Arial,sans-serif}.page{width:210mm;min-height:297mm;padding:18mm 16mm 15mm;background:#fffdf9;page-break-after:always;position:relative;overflow:hidden}.page h2{font-family:'Cormorant Garamond',Georgia,serif;font-size:30px;margin:0 0 14px;color:#173f3a}.page p{font-size:15px;line-height:1.75;white-space:pre-line}.cover{display:flex;flex-direction:column;justify-content:center;text-align:center}.cover .brand{position:absolute;top:18mm;left:16mm;font-family:'Cormorant Garamond',serif;font-size:34px;color:#1c7568}.cover h1{font-family:'Cormorant Garamond',serif;font-size:50px;line-height:1;margin:0 0 12px}.client{margin:28px auto 0;text-align:left;border:1px solid #e7e2d9;border-radius:16px;padding:18px 22px;width:75%;background:#fff}.client h2{font-size:24px}.palm-img{width:100%;max-height:135mm;object-fit:contain;border-radius:16px;border:1px solid #e7e2d9;background:#fff}.hint{font-size:13px;color:#71827e;text-align:center}.line-notes{display:grid;grid-template-columns:1fr;gap:8px;margin-top:12px}.line-notes div,.box,.mini{border:1px solid #e7e2d9;border-radius:14px;padding:12px;background:#fff}.line-notes b{display:inline-grid;place-items:center;background:#1c7568;color:#fff;border-radius:50%;width:26px;height:26px;margin-right:8px}.line-notes strong{font-size:16px}.line-notes p{font-size:13px;margin:6px 0 0}.pdf-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.mini p{font-size:28px;font-weight:800;color:#1c7568;margin:8px 0}.box{margin-bottom:12px}.box h3{margin:0 0 6px;color:#1c7568}blockquote{font-family:'Cormorant Garamond',Georgia,serif;font-size:28px;line-height:1.5;background:#edf8f4;border-radius:18px;padding:24px}footer{position:absolute;left:16mm;right:16mm;bottom:10mm;display:flex;justify-content:space-between;color:#71827e;font-size:11px;border-top:1px solid #e7e2d9;padding-top:7px}@media print{.page{page-break-after:always}}`;
  return `<!doctype html><html lang="mn"><head><meta charset="utf-8"><title>${esc(m.name||'sara')}-palm-report</title><link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@600;700&family=Inter:wght@400;600;700;800&display=swap" rel="stylesheet"><style>${css}</style></head><body>${pages.join('')}<script>document.querySelectorAll('footer span:last-child').forEach((x,i)=>{if(!x.textContent.includes('Л.Батцог'))x.textContent=(i+1)+' / '+document.querySelectorAll('.page').length});<\/script></body></html>`;}
function openReportWindow(autoPrint=false){const html=buildPrintDocument();const w=window.open('','_blank');if(!w){alert('Popup нээгдэхгүй байна. Browser permission шалгана уу.');return null;}w.document.open();w.document.write(html);w.document.close();if(autoPrint) setTimeout(()=>{w.focus();w.print();},700);return w;}
async function downloadPDF(){openReportWindow(true)}
function printReport(){openReportWindow(true)}
function exportWord(){const html=buildPrintDocument();const blob=new Blob(['\ufeff',html],{type:'application/msword'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=((currentMeta.name||$('name')?.value||'sara').trim()||'sara')+'-palm-report.doc';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},1000)}

if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{})}
